server:
  port: 8081

mes-config-ms:
  commandes-last: 20

spring:
  datasource:
    url: jdbc:h2:mem:commandes-db
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
